//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace fcm.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("fcm.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add an interesting content. 的本地化字符串。
        /// </summary>
        internal static string AddAnInterestingContent {
            get {
                return ResourceManager.GetString("AddAnInterestingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An exception occurred when deduplicating {0}: 的本地化字符串。
        /// </summary>
        internal static string AnExceptionOccurredWhenDeduplicatingFile {
            get {
                return ResourceManager.GetString("AnExceptionOccurredWhenDeduplicatingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An exception occurred while creating the new fun.txt: 的本地化字符串。
        /// </summary>
        internal static string AnExceptionOccurredWhileCreatingTheNewFuntxt {
            get {
                return ResourceManager.GetString("AnExceptionOccurredWhileCreatingTheNewFuntxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An exception occurred while exporting fun.txt: 的本地化字符串。
        /// </summary>
        internal static string AnExceptionOccurredWhileExportingFunTxt {
            get {
                return ResourceManager.GetString("AnExceptionOccurredWhileExportingFunTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An exception occurred while opening fun.txt: 的本地化字符串。
        /// </summary>
        internal static string AnExceptionOccurredWhileOpeningFunTxt {
            get {
                return ResourceManager.GetString("AnExceptionOccurredWhileOpeningFunTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A total of {0} results were found. 的本地化字符串。
        /// </summary>
        internal static string ATotalOfNResultsWereFound {
            get {
                return ResourceManager.GetString("ATotalOfNResultsWereFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Available commands 的本地化字符串。
        /// </summary>
        internal static string AvailableCommands {
            get {
                return ResourceManager.GetString("AvailableCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command 的本地化字符串。
        /// </summary>
        internal static string Command {
            get {
                return ResourceManager.GetString("Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;content to be added&gt; 的本地化字符串。
        /// </summary>
        internal static string ContentToBeAdded {
            get {
                return ResourceManager.GetString("ContentToBeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;content to be removed&gt; 的本地化字符串。
        /// </summary>
        internal static string ContentToBeRemoved {
            get {
                return ResourceManager.GetString("ContentToBeRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} does not exist. 的本地化字符串。
        /// </summary>
        internal static string DoesNotExist {
            get {
                return ResourceManager.GetString("DoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Example 的本地化字符串。
        /// </summary>
        internal static string Example {
            get {
                return ResourceManager.GetString("Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export all content to the specified file. 的本地化字符串。
        /// </summary>
        internal static string ExportAllContentToTheSpecifiedFile {
            get {
                return ResourceManager.GetString("ExportAllContentToTheSpecifiedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [blue]F[/]un [blue]C[/]ontent [blue]M[/]anager version 的本地化字符串。
        /// </summary>
        internal static string FunContentManagerVersion {
            get {
                return ResourceManager.GetString("FunContentManagerVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 fun.txt is empty. 的本地化字符串。
        /// </summary>
        internal static string FunTxtIsEmpty {
            get {
                return ResourceManager.GetString("FunTxtIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 fun.txt not found. 的本地化字符串。
        /// </summary>
        internal static string FunTxtNotFound {
            get {
                return ResourceManager.GetString("FunTxtNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 fun.txt not found, a new one will be created. 的本地化字符串。
        /// </summary>
        internal static string FunTxtNotFoundANewOneWillBeCreated {
            get {
                return ResourceManager.GetString("FunTxtNotFoundANewOneWillBeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} has been added to fun.txt. 的本地化字符串。
        /// </summary>
        internal static string HasBeenAddedToFunTxt {
            get {
                return ResourceManager.GetString("HasBeenAddedToFunTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} has been removed from fun.txt. 的本地化字符串。
        /// </summary>
        internal static string HasBeenRemovedFromFunTxt {
            get {
                return ResourceManager.GetString("HasBeenRemovedFromFunTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import the contents of the specified file. 的本地化字符串。
        /// </summary>
        internal static string ImportTheContentsOfTheSpecifiedFile {
            get {
                return ResourceManager.GetString("ImportTheContentsOfTheSpecifiedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 is already in fun.txt. 的本地化字符串。
        /// </summary>
        internal static string IsAlreadyInFunTxt {
            get {
                return ResourceManager.GetString("IsAlreadyInFunTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 is not in fun.txt. 的本地化字符串。
        /// </summary>
        internal static string IsNotInFunTxt {
            get {
                return ResourceManager.GetString("IsNotInFunTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 List all interesting content. 的本地化字符串。
        /// </summary>
        internal static string ListAllInterestingContent {
            get {
                return ResourceManager.GetString("ListAllInterestingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No arguments 的本地化字符串。
        /// </summary>
        internal static string NoArguments {
            get {
                return ResourceManager.GetString("NoArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No matching content was found. 的本地化字符串。
        /// </summary>
        internal static string NoMatchingContentWasFound {
            get {
                return ResourceManager.GetString("NoMatchingContentWasFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No valid keywords. 的本地化字符串。
        /// </summary>
        internal static string NoValidKeywords {
            get {
                return ResourceManager.GetString("NoValidKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open fun.txt 的本地化字符串。
        /// </summary>
        internal static string OpenFunTxt {
            get {
                return ResourceManager.GetString("OpenFunTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameters 的本地化字符串。
        /// </summary>
        internal static string Parameters {
            get {
                return ResourceManager.GetString("Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please tell me what you want to search. 的本地化字符串。
        /// </summary>
        internal static string PleaseTellMeWhatYouWantToSearch {
            get {
                return ResourceManager.GetString("PleaseTellMeWhatYouWantToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please tell me where you want to export to. 的本地化字符串。
        /// </summary>
        internal static string PleaseTellMeWhereYouWantToExportTo {
            get {
                return ResourceManager.GetString("PleaseTellMeWhereYouWantToExportTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please tell me which file you want to import. 的本地化字符串。
        /// </summary>
        internal static string PleaseTellMeWhichFileYouWantToImport {
            get {
                return ResourceManager.GetString("PleaseTellMeWhichFileYouWantToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Purpose 的本地化字符串。
        /// </summary>
        internal static string Purpose {
            get {
                return ResourceManager.GetString("Purpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Randomly output an interesting content. 的本地化字符串。
        /// </summary>
        internal static string RandomlyOutputAnInterestingContent {
            get {
                return ResourceManager.GetString("RandomlyOutputAnInterestingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove an interesting content. 的本地化字符串。
        /// </summary>
        internal static string RemoveAnInterestingContent {
            get {
                return ResourceManager.GetString("RemoveAnInterestingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove duplicate lines from the content. 的本地化字符串。
        /// </summary>
        internal static string RemoveDuplicateLinesFromTheContent {
            get {
                return ResourceManager.GetString("RemoveDuplicateLinesFromTheContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Result 的本地化字符串。
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search content based on the specified keyword. 的本地化字符串。
        /// </summary>
        internal static string SearchContentBasedOnTheSpecifiedKeyword {
            get {
                return ResourceManager.GetString("SearchContentBasedOnTheSpecifiedKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;search keyword&gt; 的本地化字符串。
        /// </summary>
        internal static string SearchKeyword {
            get {
                return ResourceManager.GetString("SearchKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show this help table. 的本地化字符串。
        /// </summary>
        internal static string ShowThisHelpTable {
            get {
                return ResourceManager.GetString("ShowThisHelpTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show version information. 的本地化字符串。
        /// </summary>
        internal static string ShowVersionInformation {
            get {
                return ResourceManager.GetString("ShowVersionInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Successfully deduplicated for {0}. 的本地化字符串。
        /// </summary>
        internal static string SuccessfullyDeduplicatedFor {
            get {
                return ResourceManager.GetString("SuccessfullyDeduplicatedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Successfully exported fun.txt to {0}. 的本地化字符串。
        /// </summary>
        internal static string SuccessfullyExportedFunTxtTo {
            get {
                return ResourceManager.GetString("SuccessfullyExportedFunTxtTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Successfully imported {0}. 的本地化字符串。
        /// </summary>
        internal static string SuccessfullyImported {
            get {
                return ResourceManager.GetString("SuccessfullyImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The location of the files that need to be deduplicated; leave blank for the default location. 的本地化字符串。
        /// </summary>
        internal static string TheLocationOfTheFileThatNeedToBeDeduplicated_LeaveBlankForTheDefaultLocation {
            get {
                return ResourceManager.GetString("TheLocationOfTheFileThatNeedToBeDeduplicated_LeaveBlankForTheDefaultLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;the path of the file to be exported to&gt; 的本地化字符串。
        /// </summary>
        internal static string ThePathOfTheFileToBeExportedTo {
            get {
                return ResourceManager.GetString("ThePathOfTheFileToBeExportedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;the path of the file to be imported&gt; 的本地化字符串。
        /// </summary>
        internal static string ThePathOfTheFileToBeImported {
            get {
                return ResourceManager.GetString("ThePathOfTheFileToBeImported", resourceCulture);
            }
        }
    }
}
