name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 版本号 (不带v)
        required: true
        default: 2.3.3
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: 设置 .NET
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: 10.x

      - name: 更新版本号
        shell: bash
        env:
          GITHUB_EVENT_INPUTS_VERSION: ${{ github.event.inputs.version }}
        run: |-
          if [[ "$GITHUB_EVENT_NAME" == "workflow_dispatch" ]]; then
            version="${GITHUB_EVENT_INPUTS_VERSION#v}"
          else
            version="${GITHUB_REF_NAME#refs/tags/}"
            version="${version#v}"
          fi
          echo "版本号: $version"

          sed -i "s/^\([[:space:]]*internal const string VERSION = \)\".*\";/\1\"$version\";/" src/fcm/Commands/Version.cs
          cat src/fcm/Commands/Version.cs

          sed -i "s/^\(AppVersion=\).*/\1$version/" installer.iss
          cat installer.iss

      - name: 发布
        run: dotnet publish src/fcm/fcm.csproj --configuration Release

      - name: 打包安装程序
        shell: pwsh
        run: |-
          if ((Get-Date) -le (Get-Date "2026-06-29")) {
            Write-Host "通过 GitHub API 下载中文翻译..."
            $apiUrl = "https://api.github.com/repos/jrsoftware/issrc/contents/Files/Languages/ChineseSimplified.isl?ref=main"
            $downloadPath = "C:\Program Files (x86)\Inno Setup 6\Languages\ChineseSimplified.isl"
            Invoke-WebRequest -Uri $apiUrl -Headers @{ "Accept" = "application/vnd.github.raw+json" } -OutFile $downloadPath
            Get-FileHash -Path $downloadPath -Algorithm SHA256
          } else {
            Write-Error "Inno Setup 7.0.2 应该今天会发布，请使用包含官方翻译的新版本"
            exit -1
          }

          iscc installer.iss

      - name: 上传构建文件
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: Release/FunContentManager_Setup.exe

      - name: 发布至发行版
        env:
          GH_TOKEN: ${{ github.token }}
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: gh release upload "$env:GITHUB_REF_NAME" "Release/FunContentManager_Setup.exe" --clobber
