name: Release

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: 设置 .NET
        uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0
        with:
          dotnet-version: 10.x

      - name: 发布
        run: dotnet publish fcm --configuration Release

      - name: 打包安装程序
        shell: bash
        run: |-
          curl -o "C:\Program Files (x86)\Inno Setup 6\Languages\ChineseSimplified.isl" "https://raw.githubusercontent.com/jrsoftware/issrc/main/Files/Languages/Unofficial/ChineseSimplified.isl"
          iscc installer.iss

      - name: 上传构建文件
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          path: Release/FunContentManager_Setup.exe

      - name: 发布至发行版
        env:
          GH_TOKEN: ${{ github.token }}
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: gh release upload "$env:GITHUB_REF_NAME" "Release/FunContentManager_Setup.exe" --clobber
